version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.jvm
    ports:
      - "8080:8080"
    volumes:
      - /data:/data

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - app
