version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.jvm
    ports:
      - "8080:8080"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
